---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: printing-pipelines
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: printing-pipelines
    spec:
      containers:
        - name: printing-pipelines
          image: alpine
          command: ["ping", "8.8.8.8"]
